import { System, Entity } from '@engine/ecs';
import { IntentQueue, isIntent } from '@/state/IntentQueue';
import * as Components from '../components';
import { CivilizationRegistry } from '@engine/civilization/Civilization';
import { logger } from '@/utils/logger';
import Phaser from 'phaser';

/**
 * Manages civilization-level production.
 * Aggregates production from all cities and adds starting production per turn.
 */
export class CivilizationProductionSystem extends System {
  private intents: IntentQueue;
  private events: Phaser.Events.EventEmitter;
  private civilizationRegistry: CivilizationRegistry;
  
  // Track civilization production by civId
  private civilizationProduction: Map<string, number> = new Map();

  constructor(
    intents: IntentQueue,
    events: Phaser.Events.EventEmitter,
    civilizationRegistry: CivilizationRegistry,
  ) {
    super();
    this.intents = intents;
    this.events = events;
    this.civilizationRegistry = civilizationRegistry;
  }

  /**
   * Gets the current production for a civilization.
   */
  public getProduction(civId: string): number {
    return this.civilizationProduction.get(civId) || 0;
  }

  /**
   * Adds production to a civilization.
   */
  public addProduction(civId: string, amount: number): void {
    const current = this.civilizationProduction.get(civId) || 0;
    this.civilizationProduction.set(civId, current + amount);
  }

  /**
   * Spends production from a civilization.
   */
  public spendProduction(civId: string, amount: number): boolean {
    const current = this.civilizationProduction.get(civId) || 0;
    if (current < amount) {
      return false;
    }
    this.civilizationProduction.set(civId, current - amount);
    return true;
  }

  /**
   * Initializes production for a civilization from config.
   */
  public initializeCivilization(civId: string): void {
    const civ = this.civilizationRegistry.get(civId);
    const startingProduction = civ?.startingProduction || 0;
    
    if (startingProduction > 0) {
      this.civilizationProduction.set(civId, startingProduction);
      logger.debug(`Initialized ${civId} with ${startingProduction} starting production`);
    } else {
      this.civilizationProduction.set(civId, 0);
    }
  }

  update(_dt: number): void {
    // Process production at the start of each turn
    const turnBegan = this.intents.peek(isIntent('TurnBegan'));
    if (!turnBegan) return;

    // Group cities by civilization
    const citiesByCiv = new Map<string, Entity[]>();
    const cities = this.world.view(
      Components.City,
      Components.Resources,
      Components.CivilizationComponent,
    );

    for (const cityEntity of cities) {
      const civ = this.world.getComponent(cityEntity, Components.CivilizationComponent);
      if (!civ) continue;

      if (!citiesByCiv.has(civ.civId)) {
        citiesByCiv.set(civ.civId, []);
        // Initialize civilization if not already initialized
        if (!this.civilizationProduction.has(civ.civId)) {
          this.initializeCivilization(civ.civId);
        }
      }
      citiesByCiv.get(civ.civId)!.push(cityEntity);
    }

    // Process each civilization
    for (const [civId, cityEntities] of citiesByCiv) {
      // Add starting production per turn
      const civ = this.civilizationRegistry.get(civId);
      const startingProduction = civ?.startingProduction || 0;
      if (startingProduction > 0) {
        this.addProduction(civId, startingProduction);
        logger.debug(`Added ${startingProduction} starting production to ${civId}`);
      }

      // Aggregate production from all cities' resources
      // This production was generated by YieldSystem and BuildingYieldSystem
      let totalCityProduction = 0;
      for (const cityEntity of cityEntities) {
        const resources = this.world.getComponent(cityEntity, Components.Resources);
        if (resources && resources.production > 0) {
          totalCityProduction += resources.production;
          // Transfer production from city to civilization level
          resources.production = 0;
        }
      }

      if (totalCityProduction > 0) {
        this.addProduction(civId, totalCityProduction);
        logger.debug(
          `Added ${totalCityProduction} production from cities to ${civId} (total: ${this.getProduction(civId)})`,
        );
      }
    }

    this.events.emit('ui-update');
  }
}

